### ISSUE TITLE
[Bug]: download all button is downloading the current images and the previous ones

### ISSUE THREAD

**Issue by munyanezaarmel** [alexleybourne/chrome-extension-icon-creator#1]
I uploaded an image in jpg and then click on download all it successfully downloads all images in the zip but when I upload another in png and click on the download all button it downloads the current and the previous jpg one here is a screenshot  of the zip 
![image](https://user-images.githubusercontent.com/73389979/233035799-0074cbc6-ba0d-414c-8507-004ecebbf30d.png)

**Comment by alexleybourne** [comment]
oh weird I haven't seen this. I will try to replicate and fix this. Sorry, I didn't reply sooner. Thanks for pointing this out.

**Comment by munyanezaarmel** [comment]
it is a great project good job should i close this issue

**Comment by alexleybourne** [comment]
Thanks! I will fix this and then close the issue

I managed to replicate it

<img width="745" alt="06-05-2023at 09 32 43" src="https://user-images.githubusercontent.com/54232249/236616026-66a53b38-f71d-4a46-a9e2-41830dd1ae37.png">

**Comment by alexleybourne** [comment]
Thanks again for finding this bug. It was a simple fix and an oversight on my part.

<img width="1689" alt="06-05-2023at 09 40 44" src="https://user-images.githubusercontent.com/54232249/236616418-17400407-dd5c-4071-a660-6f0c3f4f872e.png">

**Comment by munyanezaarmel** [comment]
You are welcome
