### ISSUE TITLE
How does the image file type get selected?

### ISSUE THREAD

**Issue by Kamariw95** [alexleybourne/chrome-extension-icon-creator#2]
The code to copy is `png`, which is the preferred image type per Google. However, the files downloaded were `.jpeg`.

**Comment by alexleybourne** [comment]
If you put in a JPEG image it will return one

const getFileExtension = (mimeType) => {
  switch (mimeType) {
    case 'image/jpeg':
      return 'jpeg';
    case 'image/png':
      return 'png';
    default:
      return 'png';
  }
};

Sorry that was unclear 😅

Turning a jpeg into a png would increase file size and not all favicons are png files. Sorry for the confusion. I will update this to be clearer if I get time.  😁
